-- Add missing Lead columns if they don't exist (idempotent)
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "sentSubject" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "sentBody" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "gmailThreadId" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "opened" BOOLEAN DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "openedAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "clicked" BOOLEAN DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "clickedAt" TIMESTAMP(3);
