-- AlterTable
ALTER TABLE "Lead" ADD COLUMN "opened" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "openedAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN "clicked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "clickedAt" TIMESTAMP(3);
